Default: &defaults
  user: root
  password: root
  host: localhost
  port: 3306
  database: qvotes
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: qvotes_test
  <<: *defaults

Staging:
  database: qvotes_staging
  poolsize: 100
  <<: *defaults

Production:
  database: qvotes_production
  poolsize: 100
  <<: *defaults
